### ISSUE TITLE
Upgrade to 6.2.1 ?

### ISSUE THREAD

**Issue by MinjieTao** [dmac100/clipper#1]
Hi dmac100, 
The Java port of Clipper lib is awesome and really helpful for me and my project.
However, the current version of Clipper by Angus is 6.2.1 (on sourceforge), which fixes
some bugs I met. So I wonder if you have a plan to upgrade the Java port to 6.2.1?

Thank you,

**Comment by dmac100** [comment]
Hi,

I haven't planned to upgrade to newer versions. There seems to be a large amount of changes between these versions so it would probably require rewriting most of it. I found another Java project that uses 6.2.1 though at: http://www.lighti.de/projects/polygon-clipper-for-java/

**Comment by MinjieTao** [comment]
I see.
The Java version from lighti.de is what I want. 
Thank you for your time :)
